Add database
AdalizEentropy/java-filmorate pull request #4
Opened 2022-10-15 21:32 UTC by AdalizEentropy

1. Добавлено сохранение в БД
2. Доработана бизнес логика по работе с друзьями, жанрами и mpa
3. Добавлены новые эндпоинты для жанров и mpa
4. Добавлены тесты на DAO

2022-10-17 23:33 UTC, NikolaiDem requested changes

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        Map<Long, Film> tmpFilmMap = new HashMap<>();
(Optional)
        Map<Long, Film> tmpFilmMap = films.stream()
            .collect(Collectors.toMap(Film::getId, film -> film));

Аналогично для showAllLikesFromUserId(...)

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private List<Map<Long, Genre>> showAllFilmsGenres() {
(Optional)
Чтобы не возвращать большой список id фильмов с маппингом на жанр, можно наоборот для каждой прочитанной строки из БД найти фильм из мапы tmpFilmMap и добавить в него жанр, прочитанный из строки, например так (используется void query(String sql, RowCallbackHandler rch)):
        String sqlQuery =
                "SELECT fg.film_id, g.* " +
                "FROM film_genre fg " +
                "LEFT JOIN genres g ON fg.genre_id = g.genre_id;";

        jdbcTemplate.query(sqlQuery, rs -> {
            Genre genre = getGenre(rs);
            film.addGenre(genre);
        });


Аналогично для UserDbStorage.findAllFriends().

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        for (Genre genre : genres) {
Для минимизации запросов к БД можно использовать jdbcTemplate.batchUpdate(...). А проверка на существование записи в таблице тогда заменится вызовом deleteFilmGenres(...) перед выполнением апдейта.

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public void addLike(Film film, Long userId) {
При добавлении и удалении лайков лучше сразу обновлять rate у фильма.

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        Map<Long, Film> tmpFilmMap = new HashMap<>();
Дублирующиеся части кода (такое же есть и в findAll()) лучше вынести в отдельный метод.

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            String updateFriend =
Здесь статус дружбы обновится у пользователя friendId во всех отношениях с друзьями?

2022-10-17 23:33 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                "JOIN (SELECT * " +
Попробовать сделать без вложенного селекта.

2022-10-18 18:28 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        Map<Long, Film> tmpFilmMap = new HashMap<>();
Круто! =)

2022-10-18 20:21 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private List<Map<Long, Genre>> showAllFilmsGenres() {
Done

2022-10-18 20:22 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        Map<Long, Film> tmpFilmMap = new HashMap<>();
Done

2022-10-19 17:39 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                "JOIN (SELECT * " +
Done

2022-10-19 18:07 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        for (Genre genre : genres) {
Done

2022-10-19 18:50 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public void addLike(Film film, Long userId) {
Done

2022-10-19 18:58 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            String updateFriend =
Ой... исправила =)

2022-10-20 00:25 UTC, NikolaiDem approved these changes

2022-10-20 00:25 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        String sqlQuery = "SELECT u.* " +
Интересный подход)

2022-10-25 14:37 UTC, merged